spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mutsamarket
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        use_sql_comments: true
#        show_sql: true
#        format_sql: true
  profiles:
    active: dev


jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesasdfqve

file:
  dir: /Users/changminoh/Desktop/Project_1_OhChangMin/src/main/resources/static/images/